Wod3
USEPA/useeio-widgets pull request #67
Opened 2021-07-30 07:22 UTC by TheTisiboth

All the different features are references by the Issues ID in the commit message

2021-08-03 00:27 UTC, WesIngwersen commented
@TheTisiboth @LorenHeyns  This code is updated for v1.1 of the USEEIO_API, but the USEEIO_API on the production server has not been updated yet ..it's still at v1.0.  The main issue is that this version is trying to call the `N` matrix but this doesn't yet exist on the production API - it is still called the `U` matrix in that version.  So  this code in this branch needs to be reverted back to use U in order to test and (if passing otherwise), merge it.

2021-08-03 00:29 UTC, WesIngwersen commented
This is a JS error i'm getting related to my previous comment when testing the local Sector List Alone widgets - it reads like a CORS error but the problem is that N.json does not exist
```
Access to XMLHttpRequest at 'file:///C:/Users/wesle/useeio-widgets-tisiboth/build/api/USEEIOv2.0/matrix/N.json' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.
api/USEEIOv2.0/matrix/N.json:1 Failed to load resource: net::ERR_FAILED
```

2021-08-24 00:29 UTC, WesIngwersen commented
@TheTisiboth . Pinging you here. These issue with the N matrix reverting back to U was never addressed, so this has not been merged yet,

2021-08-25 11:27 UTC, TheTisiboth commented
Hello @WesIngwersen. Sorry for the late answer, and this unsolved issue, but I just come back from vacation. 
I am going to roll back and use the USEEIO model v1.2, so it uses the U matrix

2021-08-25 12:30 UTC, TheTisiboth commented
It is now using the USEEIOv1.2 version. You can however switch back to the v2.0 in the future, and it will automatically use the N matrix, instead of the U one

2021-08-30 08:23 UTC, TheTisiboth commented
> 
> 
> @LorenHeyns @TheTisiboth I don't see the value with including the description of the 3 types of demand as you break them down here on this page.
> ![image](https://user-images.githubusercontent.com/5831306/131161800-58bab271-16a2-4b85-b8a4-2f3c4b3f806c.png)

@LorenHeyns wanted to have an explanation to explain the differences between a null value and a 0 value for the demand. What would you rather recommend ?

2021-08-30 08:55 UTC, msrocka approved these changes
I am not sure with applying a scaling factor on the /1USD-result matrices. For me these results should be scaled by a demand vector. It was done before when the respective analysis settings were provided via the URL parameters. But if this is how it should work I am fine with this… The number formatting could be done in a utility method so that this can be optimized in a single place. Also, it breaks when the model ID does not follow a pattern `[prefix]v[major].[minor]`, right? But for me this can be merged.

2021-08-30 08:55 UTC, msrocka commented on src/webapi.ts
> +            const modelVersion = parseInt(this._conf.model.split("v")[1]);
This is maybe a working fix for now but in general we cannot assume that the model ID always follows a pattern `[prefix]v[major].[minor]`, or can we? Better maybe just match with a regex `*v1.*` without throwing errors here?

2021-08-30 08:55 UTC, msrocka commented on src/webapi.ts
> +    async calculate(setup: CalculationSetup, scaleFactor = 1000000): Promise<Result> {
Why would applying such a scaling factor here be correct? The demand vector should scale the result so it would be better to provide a better demand vector here?

2021-08-30 08:55 UTC, msrocka commented on src/widgets/iogrid/commodity-list.tsx
> +    do {
Maybe better something like:

```ts
function formatNumber(x: number): string {
    if (!x)
        return "0.000";
    if (x > 1)
        return x.toFixed(3);
    const digits = Math.max(3, Math.ceil(Math.log10(1/x)))
    return x.toFixed(digits);
}
```

2021-08-30 08:55 UTC, msrocka commented on src/widgets/iogrid/flow-list.tsx
> +function formatNumber(r: number) {
This is the same format function as in another module. Would be good to extract this into a utility module and also replace this with a more efficient method (see the other comment).

2021-08-30 08:55 UTC, msrocka commented on src/widgets/sector-list/impacts.tsx
> +function formatDecimalNumber(r: number) {
again the format function...

2021-08-30 08:55 UTC, msrocka commented on src/widgets/sector-list/sector-list.tsx
> +    const scaleFactor = config.scale_factor ? config.scale_factor : 1000000;
I assume the scaling factor was introduced here because no demand vector was selected via the settings, right? Not sure with this...

2021-08-31 07:23 UTC, TheTisiboth commented on src/widgets/iogrid/commodity-list.tsx
> +    do {
Oh yeah thank you for this, it is way more efficient!

2021-08-31 08:40 UTC, TheTisiboth commented on src/webapi.ts
> +            const modelVersion = parseInt(this._conf.model.split("v")[1]);
You are right, I was assuming that the model ID had a predefined pattern.
However, I should throw an error if I can't find the version number, since it is used for knowing which matrix we should use (N or U), isn't it ?
Anyway, I am using the following pattern now `/v(\d*\.?\d*)/i`, to find the version number (it looks for a v followed by a number)

2021-08-31 08:59 UTC, TheTisiboth commented
> 
> 
> I get this on running npm install - not sure if it's an issue
> 
> ```
> npm WARN useeio-widgets@0.1.0 scripts['server'] should probably be scripts['start'].
> ```

No, it is just a warning, it is not important, it is just about naming convention

2021-08-31 09:03 UTC, TheTisiboth commented
> 
> 
> iotables_config.html When I select the [Sector List with Inflow and Outflow - Rubber tire manufacturing example](http://127.0.0.1:8080/iotables.html#sectors=326210&page=5), I see the sector named in the URL but I don't see it selected - its not present in the view but I would think all selected sectors should be at the top

I changed the behavior: 
If we specify as URL parameters some indicators, then the rows are sorted according to those indicators.
Otherwise, if no indicators are provided, then the rows are sorted, with the selected rows on top. Does it looks good to you ?

2021-08-31 12:40 UTC, modelearth commented
I'm seeing two different lists, depending on how I reload the following page.

https://thetisiboth.github.io/useeio-widget-builds/iotables.html#sectors=326210&page=1

If I open a new tab, paste the link and hit return, I don't see 326210 at the top.

I also don't see it at the top here:

https://thetisiboth.github.io/useeio-widget-builds/iotables.html#sectors=326210

If I then append &page=1 to the link above and hit return, I finally see Rubber Tires at the top.
If I hit reload, it goes away.

2021-08-31 14:46 UTC, TheTisiboth commented
> iotables.html#sectors=326210

It is indeed a bug, which is already fixed. Should I however remove this widget ?

2021-09-01 14:06 UTC, modelearth commented
Let's leave the old sample in there, but comment out all but one link to it.
Call that remaining link: Version without Google Material Design (or whatever is appropriate)
Change existing links to use the newer version for Tires, etc.

Since the older version is a non-material-design layout, it may be useful for stand-alone lists in the future.

I like the grey color myself rather than the red bars. You could add this as a new issue:
Show red when in the top 33.3% adverse, grey when in the middle, and green when positive 33.3%.
We're going to carry those colors over to a "nutrition" label currently in the works:
https://model.earth/io/template/

I also like how the older version aligns the text against the side margins.
Later we can try modifying the material design css.

Please place a settings widget above one of the new version pages, if we don't have that already.

2021-09-07 08:25 UTC, TheTisiboth commented
@modelearth I updated the IOChart as requested. By the way, I also updated to the latest version of Material UI (and react), so the IOChart looks a bit nicer.
Is there anything else to modify/add ?

2021-09-07 12:25 UTC, WesIngwersen approved these changes

2021-09-07 12:38 UTC, WesIngwersen commented on src/webapi.ts
> +    async calculate(setup: CalculationSetup, scaleFactor = 1000000): Promise<Result> {
@msrocka @TheTisiboth 
I agree that you can not apply a scaling factor to the calculate function.  I understood for the input-output chart that were just scaling the `D` matrix. This is simply to show per `x`  (e.g. million) dollar what the values were, instead of per dollar.

2021-09-07 12:41 UTC, WesIngwersen commented on src/webapi.ts
> +            const modelVersion = parseInt(this._conf.model.split("v")[1]);
versioning will be like 
`v1.2`
`v2.0.1` 
so a wildcard is appropriate

2021-09-07 12:44 UTC, WesIngwersen requested changes
I changed my review status. I think we still need to resolve the scaling issue.  We might need to meet about this to discuss because I'm not sure myself where all this is used. 
@TheTisiboth @msrocka @LorenHeyns

2021-09-13 10:26 UTC, TheTisiboth commented
I removed the scale factor, and addes some widget description (which is really short for now).
If you agree with this, we can merge.

2021-09-13 12:02 UTC, merged

2021-09-13 14:16 UTC, modelearth commented
Looks good to merge. Responsive columns are working. Thanks!